// 单词数据 —— 由每日科技媒体精选自动化追加更新
// date: 收录日期 | source: 来源文章 | term: 单词/短语 | phonetic: 音标
// meaning: 中文释义 | sentence: 原文例句 | sentenceCn: 例句翻译
window.WORDS_DATA = {
  "words": [
    // ===== 2026-09-07 | ZDNET: AI速度下的企业防线崩塌 =====
    {"id":"d0907-01","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"infiltration","phonetic":"/ˌɪnfɪlˈtreɪʃn/","meaning":"n. 渗透，潜入","sentence":"A public API endpoint was breached, and a reconnaissance agent was deployed to map the victim's network architecture.","sentenceCn":"一个公开API端点被攻破，侦察智能体被部署以绘制受害者的网络架构图。"},
    {"id":"d0907-02","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"credential theft","phonetic":"/krəˈdenʃl θeft/","meaning":"n. 凭证窃取","sentence":"Agents were then tasked with rifling through enterprise code repositories, leading to the theft of hard-coded tokens.","sentenceCn":"随后智能体被指派翻查企业代码仓库，导致硬编码令牌被盗。"},
    {"id":"d0907-03","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"privilege escalation","phonetic":"/ˈprɪvəlɪdʒ ˌeskəˈleɪʃn/","meaning":"n. 权限提升","sentence":"The attacker breached a secrets management system, stole master admin credentials, and obtained root system access.","sentenceCn":"攻击者入侵了密钥管理系统，窃取管理员主凭证并获得root系统访问权限。"},
    {"id":"d0907-04","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"backdoor","phonetic":"/ˈbækdɔːr/","meaning":"n. 后门（绕过安全机制的隐藏入口）","sentence":"The attacker tried to plant backdoors, but failed.","sentenceCn":"攻击者试图植入后门，但未能成功。"},
    {"id":"d0907-05","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"force multiplier","phonetic":"/fɔːrs ˈmʌltɪplaɪər/","meaning":"n. 力量倍增器","sentence":"AI is a \"force multiplier\" not just for defense, but for attackers today.","sentenceCn":"AI不仅是防御的\"力量倍增器\"，也是当今攻击者的力量倍增器。"},
    {"id":"d0907-06","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"autonomously","phonetic":"/ɔːˈtɒnəməsli/","meaning":"adv. 自主地，独立自主地","sentence":"AI models can be used to autonomously breach enterprise networks.","sentenceCn":"AI模型可被用于自主攻破企业网络。"},
    {"id":"d0907-07","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"post-compromise","phonetic":"/poʊst ˈkɒmprəmaɪz/","meaning":"n. 攻陷后（入侵成功后的阶段）","sentence":"Attackers can weaponize a victim's AI agents, using them as post-compromise infrastructure.","sentenceCn":"攻击者可以将受害者的AI智能体武器化，将其用作攻陷后的基础设施。"},
    {"id":"d0907-08","date":"2026-09-07","source":"ZDNET · AI攻击10小时全记录","term":"zero-day vulnerability","phonetic":"/ˈzɪroʊ deɪ ˌvʌlnərəˈbɪləti/","meaning":"n. 零日漏洞（尚未被公开或修补的漏洞）","sentence":"No zero-day vulnerability or novel attack method was necessary.","sentenceCn":"无需零日漏洞或新型攻击手段。"},
    // ===== 2026-09-07 | Computerworld: 英伟达收购Hugging Face =====
    {"id":"d0907-09","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"proprietary","phonetic":"/prəˈpraɪəteri/","meaning":"adj. 专有的，专利的","sentence":"Nvidia dominates AI with its GPUs, and generates billions through a proprietary approach.","sentenceCn":"英伟达凭借GPU主导AI市场，并通过专有技术路线赚取数十亿美元。"},
    {"id":"d0907-10","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"neutrality","phonetic":"/nuːˈtræləti/","meaning":"n. 中立性，中立地位","sentence":"Nvidia can accelerate it with capital and compute, but the real test is operational neutrality.","sentenceCn":"英伟达可以用资本和算力加速它，但真正的考验是运营中立性。"},
    {"id":"d0907-11","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"uncontested","phonetic":"/ˌʌnkənˈtestɪd/","meaning":"adj. 无可争议的，未受挑战的","sentence":"Hugging Face has near-uncontested market primacy over open-weight model releases.","sentenceCn":"Hugging Face在开源权重模型发布领域拥有近乎无可争议的市场首要地位。"},
    {"id":"d0907-12","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"primacy","phonetic":"/ˈpraɪməsi/","meaning":"n. 首要地位，卓越","sentence":"Hugging Face has near-uncontested market primacy over where developers go.","sentenceCn":"Hugging Face在开发者首选平台方面拥有近乎无可争议的首要地位。"},
    {"id":"d0907-13","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"diffuse","phonetic":"/dɪˈfjuːz/","meaning":"v. 扩散，传播","sentence":"Models get diffused into the ecosystem at scale.","sentenceCn":"模型大规模扩散到生态系统中。"},
    {"id":"d0907-14","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"at face value","phonetic":"/ət feɪs ˈvæljuː/","meaning":"短语 从表面上看，按字面理解","sentence":"Nvidia has said Hugging Face stays an open platform, and we'll take that at face value.","sentenceCn":"英伟达表示Hugging Face仍将是开放平台，我们将从字面上相信这一承诺。"},
    {"id":"d0907-15","date":"2026-09-07","source":"CW · 英伟达收购Hugging Face","term":"piece together","phonetic":"/piːs təˈɡeðər/","meaning":"短语 拼凑，整合（信息）","sentence":"Experts are still trying to piece together Nvidia's surprise plan.","sentenceCn":"专家们仍在试图拼凑英伟达这一出人意料的计划。"},
    // ===== 2026-09-07 | InfoWorld: OpenAI发布GPT-6 Astra =====
    {"id":"d0907-16","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"threshold","phonetic":"/ˈθreʃhoʊld/","meaning":"n. 阈值，门槛，临界点","sentence":"The model has crossed the \"Critical\" threshold for cybersecurity risk.","sentenceCn":"该模型已跨越网络安全风险的\"关键\"阈值。"},
    {"id":"d0907-17","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"deployment restrictions","phonetic":"/dɪˈplɔɪmənt rɪˈstrɪkʃənz/","meaning":"短语 部署限制","sentence":"The classification triggers additional deployment restrictions.","sentenceCn":"该分类触发了额外的部署限制。"},
    {"id":"d0907-18","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"exploit","phonetic":"/ɪkˈsplɔɪt/","meaning":"n. 漏洞利用程序 v. 利用","sentence":"Its ability to identify and develop zero-day exploits can help defenders find and patch weaknesses.","sentenceCn":"其识别和开发零日漏洞利用的能力可以帮助防御者发现和修补弱点。"},
    {"id":"d0907-19","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"invert","phonetic":"/ɪnˈvɜːrt/","meaning":"v. 使反转，颠倒","sentence":"That inverts the obvious enterprise response.","sentenceCn":"这使企业的明显反应发生了反转。"},
    {"id":"d0907-20","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"granularity","phonetic":"/ˌɡrænjuˈlærəti/","meaning":"n. 颗粒度，精细程度","sentence":"You lose granularity inside the exact system a regulator will ask to see.","sentenceCn":"在监管者要求查看的精确系统中，你失去了颗粒度。"},
    {"id":"d0907-21","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"telemetry","phonetic":"/təˈlemətri/","meaning":"n. 遥测数据，远程监测数据","sentence":"Its monitoring covers OpenAI's own deployment but nothing extends that telemetry to customers.","sentenceCn":"其监控覆盖OpenAI自身的部署，但没有将遥测数据扩展到客户。"},
    {"id":"d0907-22","date":"2026-09-07","source":"IW · OpenAI发布GPT-6 Astra","term":"vet","phonetic":"/vet/","meaning":"v. 审查，仔细核查","sentence":"It plans to loosen those restrictions for vetted defenders.","sentenceCn":"它计划为经过审查的防御者放宽这些限制。"},
    // ===== 2026-09-07 | InformationWeek: AI智能体颠覆SaaS定价 =====
    {"id":"d0907-23","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"per-seat pricing","phonetic":"/pɜːr siːt ˈpraɪsɪŋ/","meaning":"短语 按座位（人头）定价","sentence":"Per-seat pricing worked when humans were your only users.","sentenceCn":"当人类是唯一用户时，按座位定价是有效的。"},
    {"id":"d0907-24","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"shelfware","phonetic":"/ˈʃelfwer/","meaning":"n. 货架软件（买了却闲置的软件）","sentence":"Licenses sit idle because team members only occasionally use the platform.","sentenceCn":"许可证闲置，因为团队成员只是偶尔使用平台。"},
    {"id":"d0907-25","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"head count","phonetic":"/hed kaʊnt/","meaning":"短语 员工人数，人头数","sentence":"Enterprises measured software value by counting users.","sentenceCn":"企业通过计算用户数来衡量软件价值。"},
    {"id":"d0907-26","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"consumption","phonetic":"/kənˈsʌmpʃn/","meaning":"n. 消耗，消费","sentence":"Pricing built around consumption starts to reflect actual value.","sentenceCn":"围绕消耗构建的定价开始反映实际价值。"},
    {"id":"d0907-27","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"procurement","phonetic":"/prəˈkjʊərmənt/","meaning":"n. 采购","sentence":"Procurement cannot see where value is created.","sentenceCn":"采购部门无法看到价值在哪里被创造。"},
    {"id":"d0907-28","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"ration","phonetic":"/ˈræʃn/","meaning":"v. 配给，限量供应","sentence":"Teams ration access to make the math work.","sentenceCn":"团队限制访问权限以使成本说得通。"},
    {"id":"d0907-29","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"laggard","phonetic":"/ˈlæɡərd/","meaning":"n. 落后者，迟缓者","sentence":"Enterprise software has been the laggard; that is changing.","sentenceCn":"企业软件一直是落后者，但这种情况正在改变。"},
    {"id":"d0907-30","date":"2026-09-07","source":"IWk · AI颠覆SaaS定价","term":"workload","phonetic":"/ˈwɜːrkloʊd/","meaning":"n. 工作负载（计算任务）","sentence":"AI agents process requests, access systems and take action around the clock.","sentenceCn":"AI智能体全天候处理请求、访问系统并执行操作。"},
    // ===== 2026-09-07 | InfoWorld: Neoclouds对决超大规模云 =====
    {"id":"d0907-31","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"hyperscaler","phonetic":"/ˈhaɪpərˌskeɪlər/","meaning":"n. 超大规模云服务商（AWS/谷歌云/Azure）","sentence":"Can neoclouds actually take business from the hyperscalers?","sentenceCn":"Neoclouds真的能抢走超大规模云的业务吗？"},
    {"id":"d0907-32","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"bare-metal","phonetic":"/ber ˈmetl/","meaning":"adj. 裸金属的（直接访问物理硬件）","sentence":"Bare-metal access eliminates hypervisor overhead, delivering the full performance of the underlying GPU.","sentenceCn":"裸金属访问消除了虚拟机监控程序的开销，充分发挥GPU的性能。"},
    {"id":"d0907-33","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"goodput","phonetic":"/ˈɡʊdpʊt/","meaning":"n. 有效吞吐量（转化为有用工作的产能比例）","sentence":"Goodput is the fraction of AI infrastructure capacity that converts into useful training or inference work.","sentenceCn":"有效吞吐量是AI基础设施产能中转化为有用训练或推理工作的比例。"},
    {"id":"d0907-34","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"provisioning","phonetic":"/ˌprɒvɪˈʒənɪŋ/","meaning":"n. 资源调配，环境配置","sentence":"They provision in days, not the months hyperscalers quote.","sentenceCn":"它们在数天内完成配置，而非超大规模云所报的数月。"},
    {"id":"d0907-35","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"customer concentration","phonetic":"/ˈkʌstəmər ˌkɒnsnˈtreɪʃn/","meaning":"n. 客户集中度（收入依赖少数客户的风险）","sentence":"CoreWeave's lingering debts and high customer concentration have raised questions about its long-term sustainability.","sentenceCn":"CoreWeave持续的债务和高客户集中度引发了对其长期可持续性的质疑。"},
    {"id":"d0907-36","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"data egress","phonetic":"/ˈdeɪtə ˈiːɡres/","meaning":"n. 数据出口（数据迁出云平台的流量/费用）","sentence":"It introduces real complexity, data egress costs, and fragmented security management.","sentenceCn":"这引入了真正的复杂性、数据出口成本和碎片化的安全管理。"},
    {"id":"d0907-37","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"coexistence","phonetic":"/ˌkoʊɪɡˈzɪstəns/","meaning":"n. 共存，共处","sentence":"The most likely outcome is coexistence.","sentenceCn":"最可能的结果是共存。"},
    {"id":"d0907-38","date":"2026-09-07","source":"IW · Neoclouds对决超大规模云","term":"bounded victory","phonetic":"/ˈbaʊndɪd ˈvɪktəri/","meaning":"短语 有限胜利（局部而非全面的胜利）","sentence":"This is a bounded victory, not a takeover.","sentenceCn":"这是一场有限胜利，而非全面接管。"},
    // ===== 2026-09-07 | ZDNET: AI蜂群攻击预警 =====
    {"id":"d0907-39","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"harbinger","phonetic":"/ˈhɑːrbɪndʒər/","meaning":"n. 预兆，先兆，预告者","sentence":"If recent events are any harbinger of what's to come, we are woefully unprepared.","sentenceCn":"如果近期事件预示了即将到来的未来，那么我们可悲地尚未做好准备。"},
    {"id":"d0907-40","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"ephemeral","phonetic":"/ɪˈfemərəl/","meaning":"adj. 短暂的，转瞬即逝的","sentence":"Many of which will be so ephemeral that no human or machine may ever come to know of their brief existence.","sentenceCn":"其中许多智能体将如此短暂，以至于任何人类或机器都无从得知它们短暂的存在。"},
    {"id":"d0907-41","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"frontier","phonetic":"/ˈfrʌntɪər/","meaning":"adj. 前沿的（AI领域最先进的意思）","sentence":"AI frontier companies whose intent was presumably never malicious in the first place.","sentenceCn":"那些 AI 前沿公司，其初衷大概从来都不是恶意的。"},
    {"id":"d0907-42","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"unprecedented","phonetic":"/ʌnˈpresɪdentɪd/","meaning":"adj. 史无前例的，空前的","sentence":"We consider this incident to be an unprecedented cyber incident.","sentenceCn":"我们认为这一事件是史无前例的网络安全事件。"},
    {"id":"d0907-43","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"indicators of compromise","phonetic":"/ˈɪndɪkeɪtərz əv ˈkɒmprəmaɪz/","meaning":"短语 入侵指标（被攻击后留下的痕迹）","sentence":"Extract indicators of compromise, map the credentials touched, and separate genuine impact from decoy activity.","sentenceCn":"提取入侵指标，绘制被触及的凭证图谱，并将真实影响与诱饵活动区分开。"},
    {"id":"d0907-44","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"phishing-resistant authentication","phonetic":"/ˈfɪʃɪŋ rɪˈzɪstənt ɔːˌθentɪˈkeɪʃn/","meaning":"短语 防钓鱼身份验证（无法被钓鱼欺骗的认证）","sentence":"Making phishing-resistant authentication even more critical to stop these convincing attacks.","sentenceCn":"让防钓鱼身份验证变得更为关键，以阻止这些以假乱真的攻击。"},
    {"id":"d0907-45","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"open-weight models","phonetic":"/ˌoʊpən weɪt ˈmɒdlz/","meaning":"短语 开源权重模型（公开模型参数的 AI）","sentence":"That may mean having both commercial AI services and open-weight models they can run themselves.","sentenceCn":"这可能意味着企业同时需要商用 AI 服务和他们可自主运行的开源权重模型。"},
    {"id":"d0907-46","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"identity hygiene","phonetic":"/aɪˈdentəti ˈhaɪdʒiːn/","meaning":"短语 身份卫生（身份凭证的规范管理）","sentence":"As AI agents and other non-human identities proliferate, identity hygiene grows more important.","sentenceCn":"随着 AI 智能体和其他非人类身份激增，身份卫生变得愈发重要。"},
    // ===== 2026-09-07 | Computerworld: 联邦法官为Anthropic平反 =====
    {"id":"d0907-47","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"arbitrary and capricious","phonetic":"/ˌɑːrbətreri ənd kəˈpɪʃəs/","meaning":"短语 任意武断的（法律术语，指行政决定无合理依据）","sentence":"Calling the designation 'arbitrary and capricious.'","sentenceCn":"称这一指定是\"任意武断的\"。"},
    {"id":"d0907-48","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"pre-deprivation","phonetic":"/ˌpriː dɪˈprɪvəʃn/","meaning":"adj. 剥夺前的（剥夺权利之前应享有的程序权利）","sentence":"Anthropic was denied the pre-deprivation process required under the Fifth Amendment.","sentenceCn":"Anthropic被剥夺了第五修正案所要求的剥夺前程序权利。"},
    {"id":"d0907-49","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"articulable basis","phonetic":"/ɑːrˈtɪkjələbl ˈbeɪsɪs/","meaning":"短语 可阐明的依据","sentence":"Not based on any articulable basis to believe that Anthropic would actually sabotage its model.","sentenceCn":"并不是基于任何可阐明的依据去相信Anthropic会蓄意破坏其模型。"},
    {"id":"d0907-50","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"backdoor","phonetic":"/ˈbækdoːr/","meaning":"n. 后门（绕过正常认证的隐藏访问途径）","sentence":"What technological means would give rise to the so-called 'backdoors' or could otherwise allow Anthropic to 'disable' or affect Claude during a DoW operation?","sentenceCn":"何种技术手段会产生所谓的'后门'，或在国防部作业中让Anthropic能够\"禁用\"或影响Claude？"},
    {"id":"d0907-51","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"leverage","phonetic":"/ˈlevərɪdʒ/","meaning":"v./n. 利用，施加杠杆影响","sentence":"A government customer tried to use a supply chain risk designation as leverage in a contract dispute over model behavior.","sentenceCn":"政府客户试图将供应链风险指定作为合同争议中的施压筹码，争议焦点是模型行为问题。"},
    {"id":"d0907-52","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"blacklisting","phonetic":"/ˈblækˌlɪstɪŋ/","meaning":"n. 列入黑名单，封禁","sentence":"If a government CIO is relying on a vendor's contractual guardrails, this case says those commitments can potentially become the trigger for exactly the kind of blacklisting that risk registers are supposed to protect against.","sentenceCn":"如果政府 CIO 依赖某厂商的合同保护条款，此案表明这些承诺可能正好触发那种风险登记表本应防范的黑名单封禁。"},
    {"id":"d0907-53","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"amorphous","phonetic":"/əˈmɔːrfəs/","meaning":"adj. 无定形的，模糊不清的","sentence":"People can easily conflate disagreements over model behavior, usage policies, ethics, contractual restrictions, and cybersecurity into one amorphous category called 'AI risk.'","sentenceCn":"人们很容易将模型行为、使用政策、伦理、合同限制与网络安全等方面的分歧混为一谈，归入一个名为\"AI风险\"的模糊类别。"},
    {"id":"d0907-54","date":"2026-09-07","source":"CW · 联邦法官平反Anthropic","term":"concentration risk","phonetic":"/ˌkɒnsnˈtreɪʃn rɪsk/","meaning":"短语 集中度风险（过度依赖单一对象）","sentence":"Adopting any of those alternatives means a move from an independent Hugging Face to Microsoft, Amazon, or Google, so they change the concentration risk rather than eliminating it.","sentenceCn":"采用上述任何替代方案都意味着从独立 Hugging Face 转向微软、亚马逊或谷歌，因此它们改变的只是集中度风险，而非真正消除它。"},
    // ===== 2026-09-07 | InfoWorld: 情绪编程七大致命错误 =====
    {"id":"d0907-55","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"vibe coding","phonetic":"/vaɪb ˈkoʊdɪŋ/","meaning":"n. 情绪编程（用自然语言提示让 AI 生成代码）","sentence":"Vibe coding an application or an AI agent sounds too good to be true.","sentenceCn":"对一个应用或 AI 智能体进行情绪编程，听起来好得令人难以置信。"},
    {"id":"d0907-56","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"fallacy","phonetic":"/ˈfæləsi/","meaning":"n. 谬误，错误的观念","sentence":"The fallacy lies in organizations assuming AI-generated code is inherently correct instead of subjecting it to the same testing, validation, and quality standards.","sentenceCn":"错误观念在于：组织假设 AI 生成的代码天生就是正确的，而没有对其进行同样的测试、验证和质量把控。"},
    {"id":"d0907-57","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"pull request","phonetic":"/pʊl rɪˈkwest/","meaning":"n. 合并请求（开发人员向代码仓库提交的代码审查请求）","sentence":"AI pull requests have 1.4 times more critical issues and 1.7 times more major issues than when developers create the pull request.","sentenceCn":"AI 提交的合并请求含有的严重问题数量是开发者手动提交的 1.4 倍，主要问题数量是 1.7 倍。"},
    {"id":"d0907-58","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"nonfunctional requirements","phonetic":"/ˌnɒnˈfʌŋkʃənl rɪˈkwaɪərmənts/","meaning":"短语 非功能需求（性能、安全、可扩展性等要求）","sentence":"Coding agents can genuinely, significantly boost your productivity, but they're weak on nonfunctional requirements.","sentenceCn":"编程智能体确实能显著提升你的效率，但它们在非功能需求上较弱。"},
    {"id":"d0907-59","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"happy path","phonetic":"/ˈhæpi pæθ/","meaning":"n. 快乐路径（只考虑一切顺利的标准场景）","sentence":"It's usually just an open build with a happy path approach, and while this is great for minimum viable products, it is rough for production.","sentenceCn":"它通常只是一个走快乐路径的开放构建，这对最小可行产品很棒，但对生产环境来说却很粗糙。"},
    {"id":"d0907-60","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"technical debt","phonetic":"/ˈteknɪkl det/","meaning":"n. 技术债务（因选短期方案而积累的长期维护成本）","sentence":"Many ended up with the technical debt of maintaining applications across different development platforms and versions.","sentenceCn":"许多企业最终背负着在不同开发平台和版本上维护应用的技术债务。"},
    {"id":"d0907-61","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"RBAC","phonetic":"/ˌɑːr biː eɪ siː/","meaning":"abbr. 基于角色的访问控制（Role-Based Access Control）","sentence":"Create standards for role-based access controls (RBAC) and reusable software components to manage them.","sentenceCn":"建立基于角色的访问控制（RBAC）标准及管理这些控制的可复用软件组件。"},
    {"id":"d0907-62","date":"2026-09-07","source":"IW · 情绪编程七大致命错误","term":"spec-driven development","phonetic":"/ˈspɛk ˌdrɪvən dɪˈveləpmənt/","meaning":"短语 规格驱动开发（先写规格说明再生成代码）","sentence":"Spec-driven development is one way to address this gap.","sentenceCn":"规格驱动开发是填补这一空白的一种方式。"},
    // ===== 2026-09-07 | InformationWeek: 工作负载回迁本地 =====
    {"id":"d0907-63","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"cloud repatriation","phonetic":"/klaʊd ˌrɛpətriˈeɪʃn/","meaning":"n. 云回迁（将工作负载从公有云迁回本地）","sentence":"Today, CIOs and other IT leaders are repatriating certain workloads from public cloud back to on-premises or private cloud infrastructure.","sentenceCn":"如今，CIO 和其他 IT 领导者正把部分工作负载从公有云迁回本地或私有云基础设施。"},
    {"id":"d0907-64","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"egress costs","phonetic":"/ˈiːɡres kɒsts/","meaning":"短语 数据出口费用（云上数据迁出的费用）","sentence":"This is especially true for egress costs — the cost of moving data between workloads hosted by different cloud providers or within private cloud environments.","sentenceCn":"数据出口费用尤其如此——即在不同云服务商或私有云环境之间迁移数据所产生的费用。"},
    {"id":"d0907-65","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"sticker shock","phonetic":"/ˈstɪkər ʃɒk/","meaning":"n. 价格冲击（实际费用远高于预期）","sentence":"Many enterprises have experienced sticker-shock from variable cloud operating expenses, particularly data egress charges.","sentenceCn":"许多企业都被云运营支出的可变性——尤其是数据出口费用——给吓到了。"},
    {"id":"d0907-66","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"lift and shift","phonetic":"/lɪft ənd ʃɪft/","meaning":"短语 提升并迁移（不做架构改造直接搬迁）","sentence":"Lift first, measure second and optimize third.","sentenceCn":"先迁移（lift），再测量，最后做优化。"},
    {"id":"d0907-67","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"hybrid architecture","phonetic":"/ˈhaɪbrɪd ˌɑːrkɪˈtektʃər/","meaning":"n. 混合架构（云、边缘、本地相结合）","sentence":"Hybrid architecture is the future, and engineers who understand both cloud-native and on-prem environments are now some of the most valuable talent in the jobs market.","sentenceCn":"混合架构才是未来，同时懂云原生和本地环境的工程师，现在是最有市场价值的人才。"},
    {"id":"d0907-68","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"edge computing","phonetic":"/edʒ kəmˈpjuːtɪŋ/","meaning":"n. 边缘计算（在数据产生端就近计算）","sentence":"Including the cloud for elasticity, on-premises for consistency and the edge for immediacy.","sentenceCn":"包括公有云用于弹性扩展，本地用于稳定一致，边缘用于即时响应。"},
    {"id":"d0907-69","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"self-hosting","phonetic":"/sɛlf ˈhoʊstɪŋ/","meaning":"n. 自托管（企业自己运行基础设施）","sentence":"Self-hosting creates a lot of new work, and infrastructure management teams have gotten used to using the easy button.","sentenceCn":"自托管带来大量新工作，基础设施管理团队已经习惯了用\"一键按钮\"。"},
    {"id":"d0907-70","date":"2026-09-07","source":"IWk · 工作负载回迁本地","term":"the easy button","phonetic":"/ði ˈiːzi ˈbʌtn/","meaning":"短语 一键完成（比喻极其简便的解决方案）","sentence":"Infrastructure management teams have gotten used to using the easy button.","sentenceCn":"基础设施管理团队已经习惯了用\"一键搞定\"的做法。"},
    // ===== 2026-09-07 | InfoWorld: 英伟达130亿美元收购Hugging Face意味着什么 =====
    {"id":"d0907-71","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"inflection point","phonetic":"/ɪnˈflɛkʃn pɔɪnt/","meaning":"n. 拐点（趋势发生根本变化的时点）","sentence":"Open-source AI is at an inflection point.","sentenceCn":"开源 AI 正处于一个拐点。"},
    {"id":"d0907-72","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"retention program","phonetic":"/rɪˈtɛnʃn ˈproʊɡræm/","meaning":"短语 留任激励计划（通过股权等激励留住员工）","sentence":"Approximately $1 billion earmarked for an equity-based retention program for Hugging Face employees who agree to join Nvidia.","sentenceCn":"约 10 亿美元被指定用于一项基于股权的留任激励计划，面向同意加入英伟达的 Hugging Face 员工。"},
    {"id":"d0907-73","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"walled garden","phonetic":"/wɔːld ˈɡɑːrdn/","meaning":"n. 围墙花园（封闭、不与外部互通的产品生态）","sentence":"If Nvidia turned [Hugging Face] into a walled garden or an obvious funnel toward Nvidia hardware, it could undermine the community and network effects.","sentenceCn":"如果英伟达把 Hugging Face 变成一座围墙花园，或让其成为英伟达硬件的明显导流口，那将削弱其社区效应和网络效应。"},
    {"id":"d0907-74","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"network effects","phonetic":"/ˈnɛtwɜːrk ɪˈfɛkts/","meaning":"n. 网络效应（用户越多价值越大的现象）","sentence":"Nvidia could undermine the community and network effects it just paid nearly $13 billion to acquire.","sentenceCn":"英伟达可能削弱其刚刚斥资近 130 亿美元收购来的社区效应与网络效应。"},
    {"id":"d0907-75","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"clarion call","phonetic":"/ˈklæriən kɔːl/","meaning":"n. 强烈号召，响亮召唤","sentence":"This should be a clarion call for CIOs to treat Hugging Face and open source models as part of their enterprise supply chain.","sentenceCn":"这应当成为向 CIO 们发出的强烈号召：请把 Hugging Face 和开源模型视作企业供应链的一部分。"},
    {"id":"d0907-76","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"single point of dependency","phonetic":"/ˌsɪŋɡl pɔɪnt əv dɪˈpɛndənsi/","meaning":"短语 单一依赖点（不可替代的关键依赖）","sentence":"There are ways to avoid making it a single point of dependency.","sentenceCn":"有办法避免让它成为单一依赖点。"},
    {"id":"d0907-77","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"drift","phonetic":"/drɪft/","meaning":"n./v. 漂移（缓慢且不易察觉的偏移）","sentence":"The risk isn't a dramatic reverse course. It's a slow drift, where the Nvidia-optimized path quietly becomes the easy path.","sentenceCn":"风险不在于戏剧性的大转弯。而是一种缓慢的漂移——英伟达优化的路径悄无声息地成了容易路径，其他所有路径都变得费劲。"},
    {"id":"d0907-78","date":"2026-09-07","source":"IW · 英伟达130亿收购Hugging Face","term":"gravity","phonetic":"/ˈɡrævəti/","meaning":"n. 引力（此处比喻看不见但会把人拽过去的影响力）","sentence":"Nobody has to be banned for the field to tilt. Gravity is enough and gravity is the part the pledge does not mention.","sentenceCn":"要让天平倾斜，无须封禁谁。引力就足够了，而引力恰恰是承诺中没提到的部分。"},
    // ===== 2026-09-07 | ZDNET: AI蜂群攻击预警 · 副词句 =====
    {"id":"d0907-79","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"woefully","phonetic":"/ˈwoʊfəli/","meaning":"adv. 可悲地，严重地","sentence":"If recent events are any harbinger of what's to come, we are woefully unprepared.","sentenceCn":"如果近期事件预示了即将到来的未来，那么我们可悲地尚未做好准备。"},
    {"id":"d0907-80","date":"2026-09-07","source":"ZDNET · AI蜂群攻击预警","term":"proliferate","phonetic":"/prəˈlɪfəreɪt/","meaning":"v. 激增，大量繁殖","sentence":"As AI agents and other non-human identities proliferate, identity hygiene grows more important.","sentenceCn":"随着 AI 智能体和其他非人类身份激增，身份卫生变得愈发重要。"}
  ]
};
